### PR TITLE
Improve MvxCachedFragmentInfo flexibility and fix caching bugs

### PR DESCRIPTION
**Pull request by vvolkgang**
All of the small changes where made with the final objective of providing more flexibility to inheritors. Furthermore, already includes #85.
# Improvements
- You can now create your custom `MvxCachedFragmentInfo` by implementing the `IMvxCachedFragmentInfo` and overriding `MvxCachingFragmentActivity.CreateFragmentInfo(...)`. Sample used this for Transitions and to know if the fragment is one of the drawer root fragments
- Newly added `OnFragmentCreated(...)` enables you to do one time fragment setups. This was used in the sample to inflate transitions.
- `OnFragmentChanged` provides a callback so you can know when there was a change in fragments and which fragment is being presented. This is the only callback thats being called when you present a new fragment and when you go back to a previous one. Sample used this to check if the current fragment being showed is root, if so, it enables the user to interact with the menu.
- Instead of sending the fragment tag, all callbacks now send `IMvxCachedFragmentInfo`
- Added slide_left + slide_right transitions to the sample
- Everything was copypasted to the `Compat` version, the one being used in the sample
# Questions
- Does `OnFragmentChanged` needs to be called before the `FragmentTransaction.Add(...)`?
- What if in `OnBackPressed` there's multiple fragments being displayed? (for instance, phone vs tablet usecase) Show we be sending a list of tags or list of `IMvxCachedFragmentInfo` ?

### CODE REVIEW

**Comment by martijn00** [comment]
I did some testing now. There where 2 cases where i could get this to crash in the sample app:
1. Open app
2. Go to Settings screen
3. Press back button
4. Go again to settings screen: navigation fails, when clicking a bit around after that the app crashes

Crash log:

```
[MonoDroid] Java.Lang.IllegalStateException: Exception of type 'Java.Lang.IllegalStateException' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
[MonoDroid] at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) [0x00084] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1029
[MonoDroid] at Android.App.Activity.OnSaveInstanceState (Android.OS.Bundle) [0x00070] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:4460
[MonoDroid] at Cirrious.MvvmCross.Droid.Support.AppCompat.MvxEventSourceAppCompatActivity.OnSaveInstanceState (Android.OS.Bundle) [0x0000f] in c:\Users\Gebruiker\Documents\MvvmCross-AndroidSupport\Cirrious.MvvmCross.Droid.Support.AppCompat\MvxEventSourceAppCompatActivity.cs:80
[MonoDroid] at Cirrious.MvvmCross.Droid.Support.AppCompat.MvxCachingFragmentCompatActivity.OnSaveInstanceState (Android.OS.Bundle) [0x00081] in c:\Users\Gebruiker\Documents\MvvmCross-AndroidSupport\Cirrious.MvvmCross.Droid.Support.AppCompat\MvxCachingFragmentCompatActivity.cs:218
[MonoDroid] at Android.App.Activity.n_OnSaveInstanceState_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:4442
[MonoDroid] at (wrapper dynamic-method) object.9e64c9d4-826f-4788-aea2-a42287a4dd6f (intptr,intptr,intptr) <IL 0x00017, 0x00043>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.IllegalStateException: Recursive entry to executePendingTransactions
[MonoDroid]     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1473)
[MonoDroid]     at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1684)
[MonoDroid]     at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:527)
[MonoDroid]     at cirrious.mvvmcross.droid.support.appcompat.MvxCachingFragmentCompatActivity.n_onSaveInstanceState(Native Method)
[MonoDroid]     at cirrious.mvvmcross.droid.support.appcompat.MvxCachingFragmentCompatActivity.onSaveInstanceState(MvxCachingFragmentCompatActivity.java:38)
[MonoDroid]     at android.app.Activity.performSaveInstanceState(Activity.java:1373)
[MonoDroid]     at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1286)
[MonoDroid]     at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4367)
[MonoDroid]     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4326)
[MonoDroid]     at android.app.ActivityThread.access$1000(ActivityThread.java:172)
[MonoDroid]     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
[MonoDroid]     at android.os.Handler.dispatchMessage(Handler.java:102)
[MonoDroid]     at android.os.Looper.loop(Looper.java:145)
[MonoDroid]     at android.app.ActivityThread.main(ActivityThread.java:5832)
[MonoDroid]     at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid]     at java.lang.reflect.Method.invoke(Method.java:372)
[MonoDroid]     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
[MonoDroid]     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

And this:
1. Open app
2. Go to Settings screen
3. Press back button
4. Rotate screen: app crashes with same crash log

Could you look into this?

**Comment by vvolkgang** [comment]
I caught that error also but wanted to talk to you first, before this change the view would bug the tabs when you did the same, my first google hit pointed out a possible bug in the way the Examples page is doing the child fragments thus, it might be related, check this:

http://stackoverflow.com/a/7481468

I'll see if this is happening in other scenarios.

**Comment by vvolkgang** [comment]
The real problem is in #85, the way we're bringing caching fragments back. This wasn't a problem before because we were always creating new ones, that `ft.Attach` wasn't actually running in any case.

**Comment by martijn00** [comment]
We use the latest Support libraries and use child fragment manager in the sample, so i think that is not a problem.

**Comment by vvolkgang** [comment]
You're right! The problem is the way we're currently handling the detach / attach / replace of previously created fragments, it will "work again" if you unfix the #85 bug by changing [this](https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/86/files#diff-2d62057b8d4bf85011e78768c87e9249R253) line to `if(true)` but, in essence, it just worked until now because were never using the cached fragments.

**Comment by martijn00** [comment]
I've tested this a bit. When i enable add to backstack, for example on the homefragment, then pressing back takes me back to a white screen, but the menu still works. What i would expect is that after the last fragment is removed from the screen, the app navigates back to the login activity.

**Comment by vvolkgang** [comment]
Root fragments should not be added to the backstack or that will happen.
You should have a similar behavior If you handled the fragments directly.
If you only add to the backstack non root, i.e., inner fragments (which the
sample doesn't have) everything will work as expected.
On Thu, 5 Nov 2015 at 22:30, Martijn van Dijk notifications@github.com
wrote:

> I've tested this a bit. When i enable add to backstack, for example on the
> homefragment, then pressing back takes me back to a white screen, but the
> menu still works. What i would expect is that after the last fragment is
> removed from the screen, the app navigates back to the login activity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/86#issuecomment-154215930
> .
> 
> ## 
> 
> Regards,

Álison Fernandes

**Pull request merged**
