### PR TITLE
Add request null check in RunViewModelLifecycle

### PR DESCRIPTION
**Pull request by dbeattie71**

### CODE REVIEW

**Comment by dbeattie71** [comment]
Fixed some nuspecs after folder name changed.  Also renamed them to match folder name changes.

**Comment by martijn00** [comment]
There is some good stuff in here, but some comments i have:
- You updated to beta7, but that is not released yet. Only update after release otherwise packages will not be restored.
- The ID of nuspecs should not change, because then you would create a whole new package.
- Because of that the bat file should not change either.

I'll mannually merge in your changes. Thanks!

**Comment by martijn00** [comment]
Merged in #139

**Comment by dbeattie71** [comment]
Oops, didn't mean for the update part to be there.

**Pull request closed without merging**
