### PR TITLE
Replace Nuget reference with project

### PR DESCRIPTION
**Pull request by martijn00**

### CODE REVIEW

**Comment by lothrop** [comment]
Don't forget `packages.config`.

**Comment by lothrop** [comment]
And the `nuspec`.

**Comment by martijn00** [comment]
@lothrop Thanks! Done.

**Comment by lothrop** [comment]
I actually meant adding the required assemblies in the `<files>` section.

**Comment by martijn00** [comment]
Better now? ;)

**Comment by lothrop** [comment]
I don't think the last fix was needed.

**Pull request merged**
