### PR TITLE
Fix cache issue

### LINKED ISSUE #62: Restore fragments from sleep (caching issue)
When restoring fragments from sleep and then attempting to switch the visible fragment with a fragment of the same type (using force replace), the previously shown viewmodel is populated from cache and assigned to the fragment rather than my new viewmodel.

Uncommenting out https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.Fragging/MvxCachingFragmentActivity.cs#L122 fixes the problem but obviously this is then no longer a caching FragmentActivity.

What I am trying to decide is how best to correct this.  Should the fragment viewmodel be removed from cache before force replacing a fragment?  Obviously this is not an issue if you never show the same fragment in sequence.

### PR DESCRIPTION
**Pull request by andyci**
Fixes #62 

I think this is sensible fix although I accept that you could be showing the same fragment again with the same data and this change would now force a new viewmodel to be created.  Comparing bundles would be the only way to completely fix this but I suspect it would be overkill.

### CODE REVIEW

**Comment by martijn00** [comment]
What if you take `forceReplaceFragment` instead of `shouldReplaceCurrentFragment` in that `if(...)`?

Then it would still use the cache when it is the same fragment with the same viewmodel.

**Comment by andyci** [comment]
Problem there is that if you override ShouldReplaceFragment and return true then you will get the same problem

**Comment by andyci** [comment]
I'm wondering if we still need that virtual method now we have the optional forcereplace parameter.  Is it just gonna complicate things?

**Comment by cyrilcathala** [comment]
Not sure the ShouldReplaceFragment is very helpful, but it could be enhanced with a Bundle parameter, to decide if it's a new fragment or not.

**Comment by martijn00** [comment]
I think the Bundle parameter would be the better option in the end. If we use that we can also remove the forceReplaceFragment parameter.

**Comment by andyci** [comment]
Would appreciate a review of this to see if I'm on the right track.  Basically I am  pulling the MvxViewModelRequest from the cached fragment and comparing the ParameterValues to the ones in the new bundle.  I'm not sure whether the PresentationValues need to be compared too?

I've erred on the side of caution when comparing null values and forced a replace in those cases

**Comment by andyci** [comment]
Also, I left the forceReplaceFragment parameter in because there might be a need to force a replacement regardless of whether the same parameters being used in the bundle

**Comment by andyci** [comment]
I've made it so that the cache is only cleared where the same viewmodel is shown with a different bundle

**Comment by martijn00** [comment]
This would also need to be added to MvxCachingFragmentCompatActivity. I am wondering if any changes to the sample are necessary to support this.

**Comment by andyci** [comment]
Updated the compat caching fragment.  Don't think the samples should be affected as none of them seem to use the removed override ShouldReplaceFragment.

**Comment by martijn00** [comment]
Ok, so nothing is in the current samples, but maybe it would be good to add something that shows how this works so others can use it to integrate into their apps?

**Comment by andyci** [comment]
I'm not sure a sample would be particularly useful as this change is just to make sure that the user doesn't have to worry about reusing fragments when using the MvxCachingFragmentActivity.  Prior to this change it was quite glitchy as old viewmodels were being shown from the cache, etc.

**Comment by martijn00** [comment]
I've tested this a bit more, and found a bug. 

Steps:
1. Open sample app
2. Open Sidemenu and press settings
3. Press back button
4. You go back to the first screen, open sidemenu again, and press settings again
5. The settings fragment is not added, and the screen is blank

Could you look into this?

**Comment by andyci** [comment]
I've had a look and can see what the problem is.

Prior to this change, shouldReplaceFragment was true and the fragment was being recreated even though it was cached.
With this change, the fragment is instead re-attached as it already in the cache.
The question is, why can't we see the re-attached fragment?

Apparently we need to set RetainInstance=true on the fragment to make it work correctly.

The simpler fix is to return ReplaceFragmentAndViewModel if a new fragment is being shown but this defeats the purpose of caching the fragment.

**Comment by andyci** [comment]
I've checked RetainInstance and this doesn't work either so I'll change the behaviour to be the same as previously when a new fragment is shown.
Strangely this didn't occur in my project which I have been using for months!

**Comment by martijn00** [comment]
Maybe this helps: https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.V4/MvxFragmentStatePagerAdapter.cs#L50

I use the same kind of caching there, and the fragments don't need to be recreated.

**Pull request merged**
