### PR TITLE
MvxPreferenceFragmentCompat

### LINKED ISSUE #109: Inappropriate hierarchy for MvxPreferenceFragment
Hello, I am playing with the preference fragment and have found that the preference fragment should be based on the FullFragging hierarchy rather than the Support Fragging hierarchy. 

From android API reference, the v14 preference fragment has a hierarchy like this:
java.lang.object -> android.app.fragment -> android.support.v14.preference.preferencefragment
which is not from android.support.v4.app.fragment, FullFragging hierarchy should be used.

reference: https://developer.android.com/reference/android/support/v14/preference/PreferenceFragment.html

On the other hand, android has released another support library for preference fragment "PreferenceFragmentCompat" that targets API 7+ device which is inherit from android.support.v4.app.fragment, it would be nice if you guys could add support to this new API. 

reference: 
https://plus.google.com/+AndroidDevelopers/posts/9kZ3SsXdT2T

Thanks =)

### PR DESCRIPTION
**Pull request by mgj**
Introduce the MvxPreferenceFragmentCompat class. Direct copy of MvxPreferenceFragment, except it inherits from the support version instead, PreferenceFragmentCompat. Change cast in MvxFragmentStatePagerAdapter to allow using MvxPreferenceFragmentCompat in a viewpager. Resolves #109

### CODE REVIEW

**Comment by martijn00** [comment]
Thanks! In general this looks good, but i am thinking we should split up the preference library in v7 and v14 to prevent to base class issue's. What do you think of that?

**Comment by Dexyon** [comment]
@mgj and @martijn00 I would suggest that we definitely keep the V\* versions separate to keep the code clean and prevents issues in the future when we can drop certain support libraries.

**Comment by mgj** [comment]
I think we should follow the structure of the android support libraries, and since they have decided to split it into a v7.preference and v14.preference, I think its a great idea for us to do the same.

**Comment by martijn00** [comment]
I'll merge this PR then. Would you have the possibility to work on make the change in libraries?

**Comment by mgj** [comment]
Uhm, I might, but im afraid i dont know if or when that would be. :/

**Comment by martijn00** [comment]
@mgj See #132 which is a start of that. Now only the implementations need to be corrected.

**Pull request merged**
