### PR TITLE
Fix some issues with the latest fragment changes

### PR DESCRIPTION
**Pull request by andyci**
- Make MvxCachingFragmentActivity implement IMvxFragmentHost
- Make replacing the same fragment with a different request work properly
- Make Bundle required in ShowFragment() as this is needed to know what the request actually is

This needs some testing but I can confirm it works on my application and it seems to work on the samples

### CODE REVIEW

**Comment by martijn00** [comment]
Does this work with the latest changes that are not on nuget yet?

And why doesn't the MvxFragmentCompatActivity have a FragmentReplaceMode?

**Comment by andyci** [comment]
Yes this is developed against the latest code in master.
I haven't made the changes to MvxFragmentCompatActivity yet as I wanted to make sure the code was working correctly for MvxCachingFragmentActivity.

**Comment by martijn00** [comment]
I saw that https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/151 also has some changes in these classes. Can you make sure to be compatible with each other?

**Comment by dbeattie71** [comment]
@martijn00 I need to fix that pr but haven't had time yet.

**Comment by martijn00** [comment]
@dbeattie71 @andyci @thefex We need to sit together to get this fixed before the stable release of 4.0. Are you all on Slack?

**Pull request merged**
