### PR TITLE
added MvxBottomSheetDialogFragment to design support library

### PR DESCRIPTION
**Pull request by tomcurran**

### CODE REVIEW

**Comment by martijn00** [comment]
Thanks! Can you merge the upstream into your branch so the packages are updated to v23.3.0?
Also the `JsonPluginBootstrap.cs` file is not necessary in library projects since it will be included in the app code.

I am thinking about in which project this code should be since you now added a couple of new dependencies on the Design project. Any ideas on that?

**Comment by tomcurran** [comment]
As `Xamarin.Android.Support.v4` is a dependency of `Xamarin.Android.Support.Design` it seems reasonable that `MvvmCross.Droid.Support.V4` is a dependency of `MvvmCross.Droid.Support.Design`. Some of the fragment stuff, like `MvxFragmentExtensions`, comes from `MvvmCross.Droid.Support.V4`, this stuff could arguably be in a separate library. I think most of the dependencies come from `MvvmCross.Droid.Support.V4` and that we're now doing stuff with fragments. Maybe someone should check and try and remove dependencies as with `JsonPluginBootstrap.cs` I didn't realise you could get away without it.

**Comment by martijn00** [comment]
Not sure if i understood your comment correctly, but that would seems like a circular dependency to me.

I think this PR is good to merge if you remove the added packages, and only add a local reference to `v4` instead of a nuget.

**Comment by tomcurran** [comment]
I've fixed the dependencies & removed old stuff that wasn't really needed and provided from the local reference

**Comment by martijn00** [comment]
Thanks for the cool addition!

**Pull request merged**
