### PR TITLE
Added a simple LoginViewModel

### PR DESCRIPTION
**Pull request by Dexyon**
Added a simple LoginViewModel to use with the LoginActivity which used the MvxCompatActivity. This way we can use all our new components in our example. 
This is great documentation and allows us to do some regression testing when changing stuff or implementing new features.

### CODE REVIEW

**Comment by martijn00** [comment]
The main problem with this change is that you use a new activity to show login. Currently the CachingFragment implementation is limited that you first need to show some ViewModel that is connected to the Hosting Activity to show other fragments.

To work around that it is possible to just use 1 Activity and for everything else use Fragments. The real solution would be to change the code of the FragmentsPresenter to allow to navigate to the correct ViewModel directly.

Let's say you start the app, depending on if you are already logged in you want to show the LoginViewModel, or the NewsViewModel(let's imagine a news app). It doesn't make sense then that you need to show MainViewModel first in order to show the NewsViewmodel.

My guess would be we need to turn the registering of fragments around. When we call ShowViewModel we should search for if it is a fragment, and if it is so, we should search for it's parent. I was thinking that could be done by adding an attribute to fragments containing it's parent.

**Comment by Cheesebaron** [comment]
@martijn00 I think we should create a new issue discussing it there...

**Comment by martijn00** [comment]
I am going to move the example to the samples repo: https://github.com/MvvmCross/MvvmCross-Samples

I think we could improve this example project with things like this. Could you open a new PR there after i moved the sample?

**Comment by vvolkgang** [comment]
@martijn00 I think we should pull this, the sample should be improved in order to be used as a testing playground and this (given you don't clean the Activities backstack), will show the bug stated in #94.

**Comment by martijn00** [comment]
@vvolkgang Ok, no problem with me. I think we should keep this sample here anyway so we can use it for testing changes.

**Comment by martijn00** [comment]
@Dexyon could you pull in the lasted changes so this can be merged?

**Comment by vvolkgang** [comment]
@martijn00 yes, that was my point actually, improving the sample so we can use it as a testing playground and implementation example for all the features.

**Comment by Dexyon** [comment]
@martijn00 I will spend some time on it later this week. The introduction of the TvOS libraries is waiting for Xamarin to bring in TvOS library support. Will spend some time on it

**Pull request merged**
