### PR TITLE
Verifed Fixed #115, #116

### LINKED ISSUE #115: Fragment Cache rely on Fragment.Tag - not compatibile for ex. with ViewPager
We cannot use Fragment.Tag all the time to identify fragment (during cache/restore cycle).

We doesn't always have chance to give fragment our own "tag" - for example support ViewPager sets fragment tag to something like: 
android:switcher:resourceid:indexInPager

Working on issue, adding customization of that.

### PR DESCRIPTION
**Pull request by thefex**
Sorry commits contain invalid issue id.
It should be #115, and #116

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Please, don't use 'fix' and 'issue fix' as short descriptions for commits. It does not describe what is fixed. Please be more descriptive there. Thanks.

**Comment by martijn00** [comment]
Looks good to me. Can you also fix this for FullFragging?

**Comment by thefex** [comment]
Sure, I will do this before logic-refactoring issue fix. 
I'm not sure will I be able to do this today though.

**Comment by thefex** [comment]
Those commits fixes issue #113 .
Be sure to manually merge changes when nuget package of MvvmCross gets updates because it uses new IMvxMultipleViewModelCache interface.

Check pull request:
https://github.com/MvvmCross/MvvmCross/pull/1178

**Pull request merged**
