### PR TITLE
Allow extension of methods

### PR DESCRIPTION
**Pull request by Cheesebaron**

### CODE REVIEW

**Comment by martijn00** [comment]
This should also be done in the non compat version.

**Comment by Cheesebaron** [comment]
You mean in the main repo?

**Comment by martijn00** [comment]
This one: https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.Fragging/Caching/MvxCachingFragmentActivity.cs

**Comment by Cheesebaron** [comment]
Will fix that, gimme a sec

**Pull request merged**
