### PR TITLE
Added get fragment info by tag

### PR DESCRIPTION
**Pull request by mattwhetton**
Added protected method GetFragmentInfoByTag to MvxCachingFragmentCompatActivity and MvxCachingFragmentActivity

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good mostly. You should remove the `#region My additions`. Also this needs to be added to the full fragging in the main repo.

Thanks in advance!

**Comment by mattwhetton** [comment]
Apologies, rushed that in I'll get it sorted

**Comment by mattwhetton** [comment]
Ok, I removed the regions so should be good to go.

I'll get the main full fragging repo done too

**Comment by martijn00** [comment]
Thanks!

**Pull request merged**
