### PR TITLE
Make IMvxRecyclerViewHolder methods virtual, in class MvxRecyclerViewHolder 

### PR DESCRIPTION
**Pull request by zleao**

### CODE REVIEW

**Comment by martijn00** [comment]
We can accept the changes, but please use the same formatting ;)

**Comment by zleao** [comment]
Sorry.
I made the change in VS2015 and when I compared the files, it looks ok.
Only 3 lines edit. But when I do the commit/sync and then go to the github
site, he assumes that the whole file was change (formatting). Not sure how
to prevent this from happening...

**Comment by martijn00** [comment]
Don't worry, i'll just merged it, we'll fix the formatting some time.

**Comment by kjeremy** [comment]
Looks like line ending changes to me.  I'll pull in the `.gitattributes` from MvvmCross so we're at least consistent between projects.

**Comment by zleao** [comment]
I'm doing the changes directly in github site. i'll commit them in a sec...

**Comment by kjeremy** [comment]
Don't do that.  Make sure they compile on your machine first.  Though it looks like @martijn00 already merged.

**Comment by martijn00** [comment]
Hehe, yeah i already merged. But the .gitattributes sounds good! Could you also add that to the other repos @kjeremy ?

**Comment by zleao** [comment]
Yep. already merged :)
Thanks!

**Pull request merged**
