### PR TITLE
Fix bindings when using MvxAppCompatActivity

### PR DESCRIPTION
**Pull request by Cheesebaron**

### CODE REVIEW

**Comment by martijn00** [comment]
I've added that manually, and that was why bindings worked for me, but should we add it to MvxCachingFragmentActivityCompat too?

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Samples/Example.Droid/Activities/MainActivity.cs#L31

**Comment by Cheesebaron** [comment]
Yes

**Comment by Dexyon** [comment]
Tested it with the AppCompat and it works. Thanks @Cheesebaron

**Comment by Cheesebaron** [comment]
Why do we even need the FragmentActivity? AppCompatActivity handles everything...

**Comment by Dexyon** [comment]
@Cheesebaron Nice cleanup. I was wondering what all new classes were ment for. Who did insert those anyway?

**Comment by Cheesebaron** [comment]
Git blame says @martijn00 added the `MvxFragmentActivityCompat` and `MvxActivityCompat`

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blame/master/Cirrious.MvvmCross.Droid.Support.AppCompat/MvxFragmentActivityCompat.cs

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blame/master/Cirrious.MvvmCross.Droid.Support.AppCompat/MvxActivityCompat.cs

I asked on JabbR why they were needed the answer was:

> @Cheesebaron i guess we have those for easy compatiblity

What that exactly means I have no idea. I am not sure which compatibility it provides. I don't like duplicates and strange classes which are not needed when there is one class to rule them all.

@martijn00 might enlighten us :smiley:

**Comment by Dexyon** [comment]
Maybe clear the confusion and merge these requests for another alpha?

**Comment by martijn00** [comment]
Let me enlighten you! What i ment with that was: people currently might use something like `MvxActivity`, If we as naming convention just put `Compat` after that name for all the classes, people can just switch easily by adding `Compat` to the name.

**Comment by martijn00** [comment]
Can you add the:

```
protected override void AttachBaseContext(Context @base)
    {
        base.AttachBaseContext(MvxContextWrapper.Wrap(@base, this));
    }
```

To `MvxCachingFragmentActivity` in this PR too?

**Comment by Cheesebaron** [comment]
I think we should let people know that AppCompatActivity just handles everything now, unless they want their fragments cached. No need to derp around with adding new endings to duplicate classes. I don't like that.

**Comment by martijn00** [comment]
I agree. I've added a bullet for adding some documentation before release in the release issue: https://github.com/MvvmCross/MvvmCross/issues/1052

**Comment by Cheesebaron** [comment]
I am pulling the trigger here and going to merge this!

**Pull request merged**
