### PR TITLE
Appcompat spinner

### PR DESCRIPTION
**Pull request by kjeremy**
Add a tint aware version of `MvxSpinner` to activities that support AppCompat.  Replaces `MvxSpinner` on inflation.

To make this bind properly to `SelectedItem` call `MvxAppCompatSetupHelper.FillTargetFactories` from your `MvxSetup.FillTargetFactories`.

### CODE REVIEW

**Comment by martijn00** [comment]
Wouldn't it be possible to do with MvxActivityCompat like you do with setup: that the user itself need to call the helper if he uses MvxSpinner? This would prevent the activity getting messy.

**Comment by kjeremy** [comment]
I'm not sure I understand.  If you're using `MvxActivityAppCompat` you're going to want to use the AppCompat styled spinner.  All the other AppCompat widgets are swapped in for you already (ie you'll be using `AppCompatEditText`, `AppCompatButton` etc.)

**Comment by martijn00** [comment]
You are right about all the other widgets, but what i mean is: what if you don't use the spinner at all? Then this code would not be necessary. So what i would do is remove it from `MvxActivityAppCompat` and let the user add it to their activity when they need it.

**Comment by kjeremy** [comment]
The code in `OnCreateView`?

It's not hurting anything by being there if you're worried about performance (a lot goes on during inflation and an `if` check is tiny... you should see what `AppCompatDelegate` is doing anyway, this change actually short-circuits that) and the user is going to want it the moment they need a spinner.  If you were to use a normal `Spinner`  instead of an `MvxSpinner` it would get swapped out for an `AppCompatSpinner` by `AppCompatDelegate`.  This is doing the same thing but for an `MvxSpinner`.  Making this opt-in will have all of us who use `AppCompatActivity` and co have to duplicate this code.

**Comment by martijn00** [comment]
Hmm ok, good explanation! Then it is good to merge i think.

**Pull request merged**
