### PR TITLE
Use inflated view when passing it into CompatDelegate

### PR DESCRIPTION
**Pull request by Dexyon**
Created a new pull request to adjust only fix the bug instead of introducing not needed classes. 

@kjeremy I left the license for you :)

### CODE REVIEW

**Comment by Dexyon** [comment]
@Cheesebaron I couldn't think of any reasons why we shouldn't.

**Comment by martijn00** [comment]
@Dexyon @Cheesebaron look at the example of Google: https://android.googlesource.com/platform/development/+/master/samples/Support7Demos/src/com/example/android/supportv7/app/AppCompatPreferenceActivity.java

They don't override it there either: not sure why, but to me it seems we should follow that.

**Comment by Dexyon** [comment]
@martijn00  @Cheesebaron  Mmm I see. Still curious why it isn't overridden. I should adjust my PR to match the example and paste the source so nobody makes the same mistake.

**Comment by Dexyon** [comment]
@martijn00 @Cheesebaron and fixed

**Comment by kjeremy** [comment]
@Dexyon What is the bug that this solves?

**Comment by Dexyon** [comment]
@kjeremy When the SetContentView is called with a resourceId the binding isn't inflated and bindings don't work on the UI. The view is inflated as if no Mvx commands have been used.  

In my test set-up you can test it by disabling the code and run the example droid project. You will see the button doesn't work. When enabling the code again, binding does work.

**Comment by kjeremy** [comment]
Okay that makes sense to me.

@martijn00 did you get hit by this too?

I tested with my own `MvxAppCompatActivity` which does the `BindingInflate` like this PR and then calls the base `SetContentView(view)` which is why I didn't get hit by this.

:+1:

**Comment by Dexyon** [comment]
We actually do use a same approach in one our apps which is going towards production and this is hit by the same error. So if your tests are not affected by this change I would suggest merging it.

**Comment by Cheesebaron** [comment]
I'm going to merge it. If it breaks something revert it :D

**Pull request merged**
