### PR TITLE
Updated MvxRecyclerView

### PR DESCRIPTION
**Pull request by Johan-dutoit**
Allows the user to override the LayoutManager used.

### CODE REVIEW

**Comment by martijn00** [comment]
I am not seeing why this should be changed. It currently is possible to set the layoutmanager with `SetLayoutManager`

**Comment by Johan-dutoit** [comment]
That is correct, however do we want it to create two layout managers?

The one in the constructor and the other when we call SetLayoutManager.

**Comment by kjeremy** [comment]
I don't understand this change.  Isn't `LayoutManager` null in the constructor?

**Comment by Johan-dutoit** [comment]
There is a new virtual property that creates it?  Which the user can
override to whatever they want?

Instead of having the new in the 'ctor' and then again when calling
'SetLayoutManager'.

**Pull request closed without merging**
