### PR TITLE
Fix Memory Issues

### PR DESCRIPTION
**Pull request by kjeremy**
This PR corresponds with https://github.com/MvvmCross/MvvmCross/pull/1446 and should be pulled in after that change is accepted.

Together these two PRS fix:
https://github.com/MvvmCross/MvvmCross/issues/1444
https://github.com/MvvmCross/MvvmCross/issues/1405
#280

### CODE REVIEW

**Comment by inormis** [comment]
@kjeremy how to understand when this fix will be released?

**Comment by kjeremy** [comment]
It's in the latest release. Please make sure you are using the latest
MvvmCross.

**Comment by inormis** [comment]
We are using v4.3. I was sure my colleague has updated MVVMCross to 4.4 version. I'll upgrade it and will come back in 1-2 days with news. Thank you!

**Comment by inormis** [comment]
@kjeremy  it's still reproducible. But can it be caused by our implementation?

Our Viewmodels for fragments and tabs derive from MvxViewModel. But we also have viewmodels for children objects (for example ViewModel that exposes exchange rates). They derive from our **BaseNotificationViewModel** (_it came from Desktop app_). It provides **RaisePropertyChanged** methods that invoke PropertyChanged events (nothing more). Most of the frequent property changes are done using BaseNotificationViewModel. So, can it lead to bug with SetTextFormatted?

**Comment by kjeremy** [comment]
This is a pull request, not an issue, so I'm not quite sure what you are seeing.  Please open a **new** issue and point to me to a reproducible test case and I will investigate.

**Pull request merged**
