### PR TITLE
Fix inflation of views

### LINKED ISSUE #60: LayoutInflater
I don't know whether this is a new issue caused by changes in MvvmCross 4.0.0.0-beta2 but when I try and show a fragment I get:

```
java.lang.ClassNotFoundException: Didn't find class "android.view.MvxListView" on path:
```

This was working fine in 3.5.1 before the fragments were moved into the support package

### PR DESCRIPTION
**Pull request by andyci**
Fixes #60

### CODE REVIEW

**Comment by andyci** [comment]
Don't merge yet.  WIP

**Comment by andyci** [comment]
Ok this seems to be all that is needed to fix the problem.  Ready to merge

**Comment by martijn00** [comment]
I am wondering if this also is needed on the `MvxCachingFragmentActivity` and `MvxTabsFragmentActivity` and what about this in the main repo?

**Comment by andyci** [comment]
Both of those inherit from MvxFragmentActivity so I assume they will pick up this behaviour anyway?

**Comment by martijn00** [comment]
Aah that is right! But what about the main repo?

**Comment by andyci** [comment]
I agree with that, I will copy the change to the main repo as well

**Comment by andyci** [comment]
Issue doesn't exist in main repo as there is no MvxFragmentActivity

**Pull request merged**
