### PR TITLE
All output directories now the same

### PR DESCRIPTION
**Pull request by mattwhetton**
Re-pointed all 4 output directories to the same path. 

Actually just updated Cirrious.MvvmCross.Droid.Support.AppCompat and Cirrious.MvvmCross.Droid.Support.V4 to output to the same as the others.

### CODE REVIEW

**Comment by martijn00** [comment]
I think the nuspecs should point to the release folder in bin. Could you fix that too?

**Comment by mattwhetton** [comment]
It looks like the Release and Debug paths are actually pointing to different paths, 
Debug looks like this: "....\bin\Debug\Mvx\Droid\"
Release looks like this:  "bin\Release\"

Should they both be in the same place?

**Comment by martijn00** [comment]
Yes they should be at the same, which is the `root folder / bin / release / Mvx / Droid /` and `root folder / bin / debug / Mvx / Droid /`

In the main repo you can see it here: https://github.com/MvvmCross/MvvmCross/blob/4.0/nuspec/MvvmCross.HotTuna.CrossCore.nuspec#L109

**Comment by mattwhetton** [comment]
Ok great, I'll get it all lined up

**Comment by mattwhetton** [comment]
Ok these should be correct now

The release and debug branches all point to a consistent path (i.e. the one specified above).

The nuspecs actually pick up from a slightly different path (i.e. bin folder in the repo root). The files are copied there using a post build action. So I haven't changed the nuspecs as they should be working as expected.

**Comment by martijn00** [comment]
Seems correct! I'll merge it in now. @Cheesebaron please ping me if something doesn't work after this change when you upload the next nuget release.

**Pull request merged**
