### PR TITLE
Fragments which contain MvxFragmentAttribute auto-register to cache

### PR DESCRIPTION
**Pull request by thefex**
This Pull Request fixes issues #115 
Fragment should not be registered to cache with Register<> now.

Quick note how to use caching now.
Three cases:
1. I am providing Fragment tag during Fragment transaction
You doesn't have to do anything besides adding MvxFragmentAttribute to Fragment which you would like to cache
2. I do not provide Fragment tag during Fragment transaction
Your IMvxFragmentView (MvxFragment probably) should override: UniqueImmutableCacheTag string property. Let it return something like "MyCachedFragment"
3. I do not provide Fragment tag but Fragment tag is managed by some other control. Example is using cache with ViewPager
As in case "1" - just add MvxFragmentAttribute to Fragment and enjoy caching!

### CODE REVIEW

**Comment by thefex** [comment]
By the way you can always override UniqueImmutableCacheTag if you don't want to use Fragment tags. It's better to leave it to Fragment.Tag in case you're using ViewPager though - because of that you can have multiple instances of same fragment type (they can be differentiated by Fragment.Tag set by internal ViewPager implementation)

**Comment by thefex** [comment]
Issue #128 fixed with commit 64527f4

**Comment by martijn00** [comment]
How is this going @thefex ?

**Comment by thefex** [comment]
I'm back! working hard to finish it till 2am

**Pull request merged**
